### ISSUE TITLE
About the image scale and frame interval of ScanNet dataset

### ISSUE THREAD

**Issue by sharinka0715** [HLinChen/GNeSF#2]
Hello! I would like to know the image scale and the frame interval when training your GNeSF on ScanNet dataset. 

The original size of RGB images are 1296x968, with 1000+ frames in one video clip, training on which would cause high computational cost.

Have you downscaled the image size or extract the image every N frames? Or you just train them with the original dataset?

Thanks!

**Comment by HLinChen** [comment]
I have downscaled the image size to 640 x 480. Also, I extract the image about every 10 frames.
