### ISSUE TITLE
About generate_gt.py for TSDF.

### ISSUE THREAD

**Issue by YooWang** [HLinChen/GNeSF#3]
Thank you very much for your wonderful work. I wonder if you have encountered the following problems when running tools/tsdf_fusion/generate_gt.py:
pycuda._driver.LogicError: cuMemAlloc failed: invalid device context, or, pycuda._driver.LogicError: cuCtxSynchronize failed: an illegal memory access was encountered.
Thank you very much and looking forward to your reply.

**Comment by YooWang** [comment]
我根据<Data Preperation for ScanNet>描述的运行genertate_gt的脚本，但是一直会碰到pycuda._driver.LogicError: cuMemAlloc failed: invalid device context， 或者参考相关的工作修改后，也会有pycuda._driver.LogicError: cuCtxSynchronize failed: an illegal memory access was encountered，请问你碰到类似的问题吗？ 可以稍微详细描述一下你获得tsdf的操作过程吗？

**Comment by HLinChen** [comment]
Sorry, I haven't had a similar issue. But I  have uploaded the compressed folder and you can download it from here. (https://drive.google.com/file/d/19ZICAVjVoRYDE2skSDLWvKHKQpoqd2Dp/view?usp=sharing)

**Comment by YooWang** [comment]
Thank you very much!

**Comment by Andreyao** [comment]
Thank you very much for the compressed folder you provided last time. Can you provide the corresponding TSDF file of the scannet test? The last compressed folder only contained train data. Thank you so much!
