### ISSUE TITLE
'cam_info_all.pth'

### ISSUE THREAD

**Issue by YooWang** [HLinChen/GNeSF#4]
Thank you for sharing your wonderful work, I would like to know where the ‘cam_info_all.pth’ mentioned here is described? Or where download it? Thank you so much！        
cam_info_all = torch.load(os.path.join(self.args.datadir, 'scannet', 'cam_info_all.pth'))[https://github.com/HLinChen/GNeSF/blob/e80cd27d86072f4a48b538ff961fd3a0ca16cbac/GNeSF-2D/gnesf/data_loaders/scannet.py#L366C12-L366C12](https://github.com/HLinChen/GNeSF/blob/e80cd27d86072f4a48b538ff961fd3a0ca16cbac/GNeSF-2D/gnesf/data_loaders/scannet.py#L366C12-L366C12)

**Comment by HLinChen** [comment]
You can download it from here (https://drive.google.com/file/d/1ia737h8ELF5OMEjiguN6ty_nHfuueIq_/view?usp=drive_link).

**Comment by YooWang** [comment]
Thank you very much, I have applied.
