### ISSUE TITLE
About training data sets and training weights

### ISSUE THREAD

**Issue by YooWang** [HLinChen/GNeSF#5]
Are the complete scannet datasets used for training in both Semantic View Synthesis and 3D Semantic Segmentation tasks? Can you provide the final weights obtained after completing the training of these two tasks? Can be used to execute eval, thank you very much！

**Comment by HLinChen** [comment]
For the first question, yes. And I will release the weights after 15/03 if you are not urgent.

**Comment by YooWang** [comment]
Thank you very much for the reply. Looking forward to uploading the weights.  Dataset of this size is difficult to train for me， Thank you very much. And, by the way, in the task of 3D Semantic Segmentation, how is the training dataset used?
There is an additional question. In the 3D Semantic Segmentation task, does the Semantics Soft Voting part correspond to the class GeneralRenderingNetwork in the code? [https://github.com/HLinChen/GNeSF/blob/main/GNeSF-3D/models/mlp_network.py#L26](url)

**Comment by HLinChen** [comment]
You can download the checkpoints from the [link](https://drive.google.com/drive/folders/1UEoAweSwI6B2q0ChTmN9e-N31WIF_2AP?usp=drive_link).

**Comment by YooWang** [comment]
Thank you!
